spring.application.name=ms_matching
server.port=8083

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/petrescue_db
spring.datasource.username=user_admin
spring.datasource.password=password123

# JPA Config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Radio máximo de búsqueda geográfica en kilómetros (configurable)
matching.radio.max-km=10.0
# Umbral mínimo de score para considerarse coincidencia (0.0 - 1.0)
matching.score.minimo=0.4